services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.3
    command: ["start-dev", "--import-realm"]
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HOSTNAME: http://host.docker.internal:8080
      KC_HOSTNAME_STRICT: "false"
    ports:
      - "8080:8080"
    volumes:
      - ../../infra/keycloak/zerotrust-realm.json:/opt/keycloak/data/import/zerotrust-realm.json:ro
